<?php
/**
 * AdminApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Tripartie\SafeCheckout
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Safe Checkout
 *
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.22
 * Contact: noc@tripartie.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tripartie\SafeCheckout\Test\Api;

use \Tripartie\SafeCheckout\Configuration;
use \Tripartie\SafeCheckout\ApiException;
use \Tripartie\SafeCheckout\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdminApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tripartie\SafeCheckout
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdminApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiInvitePost
     *
     * Organization invite.
     *
     */
    public function testApiInvitePost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrganizationsGetCollection
     *
     * Retrieves the collection of Organization resources..
     *
     */
    public function testApiOrganizationsGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrganizationsIdGet
     *
     * Retrieves a Organization resource..
     *
     */
    public function testApiOrganizationsIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersGetCollection
     *
     * Retrieves the collection of User resources..
     *
     */
    public function testApiUsersGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersIdDelete
     *
     * Removes the User resource..
     *
     */
    public function testApiUsersIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersIdGet
     *
     * Retrieves a User resource..
     *
     */
    public function testApiUsersIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersIdPatch
     *
     * Update your profile.
     *
     */
    public function testApiUsersIdPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersIddisablePatch
     *
     * Updates the User resource..
     *
     */
    public function testApiUsersIddisablePatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersIdemailPatch
     *
     * Update user email.
     *
     */
    public function testApiUsersIdemailPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersIdemailValidationPatch
     *
     * Validate email ownership.
     *
     */
    public function testApiUsersIdemailValidationPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersIdenablePatch
     *
     * Updates the User resource..
     *
     */
    public function testApiUsersIdenablePatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersIdpasswordPatch
     *
     * Change your password.
     *
     */
    public function testApiUsersIdpasswordPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersIdtotpSetupPatch
     *
     * Setup an additional authentication factor.
     *
     */
    public function testApiUsersIdtotpSetupPatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiUsersIdtotpTogglePatch
     *
     * Disable the second authentication factor.
     *
     */
    public function testApiUsersIdtotpTogglePatch()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
