<?php
/**
 * OrganizationApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Tripartie\SafeCheckout
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Safe Checkout
 *
 * Simple, yet elegant web interfaces for your convenience. One request away from your first secured C2C transaction.
 *
 * The version of the OpenAPI document: 2.0.12
 * Contact: noc@tripartie.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Tripartie\SafeCheckout\Test\Api;

use \Tripartie\SafeCheckout\Configuration;
use \Tripartie\SafeCheckout\ApiException;
use \Tripartie\SafeCheckout\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OrganizationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Tripartie\SafeCheckout
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrganizationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiOrganizationsGetCollection
     *
     * Retrieves the collection of Organization resources..
     *
     */
    public function testApiOrganizationsGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiOrganizationsIdGet
     *
     * Retrieves a Organization resource..
     *
     */
    public function testApiOrganizationsIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
